# Generated by Django 5.0.4 on 2024-04-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_site', models.TextField()),
                ('image_for_carousel', models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('logo', models.ImageField(blank=True, default=None, upload_to='photos', verbose_name='Фото')),
            ],
        ),
    ]
