# Generated by Django 5.0.4 on 2024-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_text_photo_about_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_photo',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='text_photo',
            name='about_site',
            field=models.TextField(blank=True, default=None),
        ),
    ]
