# Generated by Django 5.0.4 on 2024-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_text_photo_is_published_alter_text_photo_about_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.CharField(blank=True, default=None, max_length=100)),
                ('playstation', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
    ]
