# Generated by Django 5.0.4 on 2024-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.CharField(blank=True, default=None, max_length=100)),
                ('main', models.CharField(blank=True, default=None, max_length=100)),
                ('ps', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
    ]
